name: fetch-sheets
on: push
run-name: Fetch migration data from (public) google sheets
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - id: 'fetch_sheet'
        uses: 'jroehl/gsheet.action@v1.0.0'
        with:
          spreadsheetId: '1eJk-J_UwVQ3qdCAqPKQ49sKff7dnKTfxfGf5E2GRvBE'
          commands: |
            [
              { "command": "getSpreadsheet", "spreadsheetId": "1eJk-J_UwVQ3qdCAqPKQ49sKff7dnKTfxfGf5E2GRvBE" }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: write sheet to local file
        env:
          RESULTS: ${{ steps.fetch_sheet.outputs.results }}
        run: echo "$RESULTS" > data/sheets.json
      - name: commit changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: '${{ secrets.GH_TOKEN }}'
          commit_message:
            Data update triggered by ${{ github.actor }}
